- README.md
Related: https://github.com/JakobJingleheimer/nodejs-loaders/issues/13
> doc(mismatched-format): add note about Node.js's builtin support

- .github/workflows/publish.yml
Tags will be `vX.X.X@packagename`
> chore(ci-publish): support provenance for monorepo

- package.json
Prepare the release of `1.1.0` before monorepo.
We only bump the minor cause changing of parser allow nested css. But it's shouldn't introduce breaking change.
> chore: bump 1.0.0 → 1.1.0

- README.md
- packages/alias/README.md
- packages/css-module/README.md
- packages/media/README.md
- packages/mismatched-format/README.md
- packages/svgx/README.md
- packages/text/README.md
- packages/tsx/README.md
Thanks to this pr, the readme uses gh raw because at the moment if we publish, the npm page won't display the logo.
> chore(readme): update

- .github/workflows/ci.yml
- packages/tsx/package.json
- packages/tsx/tsx.spec.mjs
TSX loader requires `module.findPackageJSON`, which is not yet backported below 23.x (https://github.com/nodejs/node/pull/56074).
When it is backported, we'll release a patch of TSX loader to restore support.
> chore(deps, tsx): temporarily remove support for node below v23

- README.md
Aurelia is a frontend framework. And it's have it's own ESM loader. So let's mention it
> chore(README): add more "official loaders"

- .npmignore
- biome.jsonc
- packages/alias/README.md
- packages/alias/alias.mjs
- packages/alias/alias.spec.mjs
- packages/alias/alias.test.mjs
- packages/alias/fixtures/e2e.mjs
- packages/alias/fixtures/message.mjs
- packages/alias/fixtures/register-hooks.mjs
- packages/alias/fixtures/register.mjs
- packages/alias/fixtures/tsconfig.json
- utils/spawn-promisified.mjs
This now works:
```js
import module from 'node:module';
import * as aliasLoader from '@nodejs-loaders/alias';
module.registerHooks(aliasLoader);
```
as well as the current behaviour:
```js
import module from 'node:module';
module.register('@nodejs-loaders/alias', import.meta.url);
```
Note that not all of our loaders can be compatible with `module.registerHooks` because some are async.
> feat(alias loader): make compatible with `module.registerHooks`

- .github/workflows/ci.yml
Use `--run` instead of `npm run`
https://github.com/nodejs-loaders/nodejs-loaders/pull/92#discussion_r1908902158
> ci: use `node --run`

- .github/workflows/ci.yml
Not sure how this got moved into the multi-node-version job.
> setup(workflow): move `type check` to run-once job

- packages/json5/package.json
**Full Changelog**: https://github.com/nodejs-loaders/nodejs-loaders/compare/v1.0.0@json5...v1.1.0@json5
> release(json5): bumb version `1.0.0` → `1.1.0`

- packages/alias/package.json
* feat(alias): replace deprecated `lodash.get` with optional chaining by @JakobJingleheimer in https://github.com/nodejs-loaders/nodejs-loaders/pull/119
* This is a breaking change for `alias` because the main entry-point now auto-registers its hooks via the async API (`node:module.register`); consumers who were registering its hooks via the sync API (`node:module.registerHooks`) will also inadvertently (and unknowingly) register those hooks via the async API due to merely importing the file. See [Usage with …
> release(alias): bumb version `1.1.0` → `2.0.0`

- packages/svgx/package.json
* dep(svelte): bump svelte from 5.19.6 to 5.19.7 by @dependabot in https://github.com/nodejs-loaders/nodejs-loaders/pull/115
**Full Changelog**: https://github.com/nodejs-loaders/nodejs-loaders/compare/v1.0.1@svgx.. …
> release(svgx): bumb version `1.0.1` → `1.1.0`

- packages/svelte/package.json
**Full Changelog**: https://github.com/nodejs-loaders/nodejs-loaders/compare/v1.0.1@svelte...v1.1.0@svelte
> release(svelte): bumb version `1.0.1` → `1.1.0`

- packages/mismatched-format/package.json
**Full Changelog**: https://github.com/nodejs-loaders/nodejs-loaders/compare/v1.0.1@mismatched-format...v1.1.0@mismatched-format
> release(mismatched-format): bumb version `1.0.1` → `1.1.0`

- packages/jsonc/package.json
**Full Changelog**: https://github.com/nodejs-loaders/nodejs-loaders/compare/v1.0.1@jsonc...v1.1.0@jsonc
> release(jsonc): bumb version `1.0.1` → `1.1.0`

- packages/deno-npm-prefix/package.json
**Full Changelog**: https://github.com/nodejs-loaders/nodejs-loaders/compare/v1.0.1@deno-npm-prefix...v1.1.0@deno-npm-prefix
> release(deno-npm-prefix): bump version `1.0.1` → `1.1.0`

- packages/alias/package.json
* fix(alias): correct hook types by @JakobJingleheimer in https://github.com/nodejs-loaders/nodejs-loaders/pull/156
* fix(alias): support `tsconfig` as JSON5 (trailing commas, comments) by @JakobJingleheimer in https://github.com/nodejs-loaders/nodejs-loaders/pull/155
**Full Changelog**: https://github.com/nodejs-loaders/nodejs-loaders/compare/v2.0.0@alias...v2.0.1@alias
> release(alias): bumb version `2.0.0` → `2.0.1`

- packages/json5/json5.loader.mjs
We should probably have a test for these so it doesn't get missed (like it did here) 🤔
> fix(json5): set type for `resolveJSON5` (`ResolveHook`)

- packages/media/package.json
* feat(media): add `.epdb` and `.pdf` to default list of file extensions by @JakobJingleheimer in https://github.com/nodejs-loaders/nodejs-loaders/pull/174
**Full Changelog**: https://github.com/nodejs-loaders/nodejs-loaders/compare/v1.2.0@media...v1.3.0@media
> release(media): bump version `1.2.0` → `1.3.0`

- packages/alias/alias.spec.mjs
- packages/alias/alias.test.mjs
- packages/css-module/css-module.test.mjs
- packages/deno-npm-prefix/deno-npm-prefix.spec.mjs
- packages/deno-npm-prefix/deno-npm-prefix.test.mjs
- packages/json5/json5.test.mjs
- packages/jsonc/jsonc.test.mjs
- packages/media/media.test.mjs
- packages/mismatched-format/contains-cjs.spec.mjs
- packages/mismatched-format/mismatched-format.loader.mjs
- packages/mismatched-format/mismatched-format.spec.mjs
- packages/mismatched-format/mismatched-format.test.mjs
- packages/parse-filename/parse-filename.spec.mjs
- packages/svelte/svelte.test.mjs
- packages/tsx/tsx.test.mjs
This reduces total test execution time by about a third.
> test(all): parallelise case execution

- .oxlintrc.json
- packages/alias/alias.loader.mjs
- packages/alias/alias.spec.mjs
A bug introduced in alias@2.1.0 where the is promise-like check recommended by `tsc` would fail when aliased specifier did not resolve (and alias is checking whether it's part of a synchronous or asynchronous chain).
> fix(alias): unresolvable specifier should not fail on internal checks

- packages/alias/package.json
* doc(alias): fix bad markdown in readme by @JakobJingleheimer in https://github.com/nodejs-loaders/nodejs-loaders/pull/198
* fix(alias): unresolvable specifier should not fail on internal checks by @JakobJingleheimer in https://github.com/nodejs-loaders/nodejs-loaders/pull/199
**Full Changelog**: https://github.com/nodejs-loaders/nodejs-loaders/compare/v2.1.0@alias...v2.1.1@alias
> release(alias): bump version `2.1.0` → `2.1.1`

- packages/alias/alias.test.mjs
`module.registerHooks` has been back-ported as of 22.15
> test(alias): remove obsolete node23+ gate on test-case

- packages/alias/package.json
* fix(alias): subpath import key erroneously flagged as directory by @JakobJingleheimer in https://github.com/nodejs-loaders/nodejs-loaders/pull/211
* dep(node): officially support node 24.x (add to CI) by @AugustinMauroy in https://github.com/nodejs-loaders/nodejs-loaders/pull/210
**Full Changelog**: https://github.com/nodejs-loaders/nodejs-loaders/compare/v2.1.1@alias...v2.1.2@alias
> release(alias): bump version `2.1.1` → `2.1.2`

- packages/tsx/package.json
* dep(node): support node v24.x by @AugustinMauroy in https://github.com/nodejs-loaders/nodejs-loaders/pull/210
* fix(windows): allow for windows support by @avivkeller in https://github.com/nodejs-loaders/nodejs-loaders/pull/189
* @avivkeller made their first contribution in https://github.com/nodejs-loaders/nodejs-loaders/pull/189
**Full Changelog**: https://github.com/nodejs-loaders/nodejs-loaders/compare/v1.1.1@tsx...v1.1.2@tsx
> release(tsx): bump version `1.1.1` → `1.1.2`
