.github/workflows/node.js.yml

update workflow for test to have 22 (current)

test: update workflow

---

.gitignore
package-lock.json

- adding `.gitignore`
- and update `package-lock.json` to accord to `package.json`

fix: package-lock + gitignore

---

README.md

doc(css-module): update README example

---

.github/workflows/ci.yml
package.json

https://github.com/marketplace/actions/coveralls-github-action

test(ci): add publish step to CI job

---

packages/alias/README.md
packages/css-module/README.md
packages/media/README.md
packages/mismatched-format/README.md
packages/svgx/README.md
packages/text/README.md
packages/tsx/README.md

Resolves https://github.com/JakobJingleheimer/nodejs-loaders/issues/3

chore(doc): fix README npm badges

---

package.json
packages/alias/package.json
packages/css-module/package.json
packages/media/package.json
packages/mismatched-format/package.json
packages/parse-filename/package.json
packages/svgx/package.json
packages/text/package.json
packages/tsx/package.json

we need to update that, IDK but I'm convinced that npm publish without this update

fix(package.json):  `repository` key

---

CODE_OF_CONDUCT.md

Since we are an "org" it's can be useful to have a code of conduct. So I just use "Citizen Code of Conduct" template

Chore(CoC): introduce

---

packages/alias/package.json
packages/css-module/package.json
packages/jsonc/package.json
packages/media/package.json
packages/mismatched-format/package.json
packages/svgx/package.json
packages/text/package.json
packages/tsx/package.json
packages/yaml/package.json

Resolves https://github.com/nodejs-loaders/nodejs-loaders/issues/69

doc: standardise package descriptions & keywords/tags

---

packages/jsonc/README.md

we hadn't seen that in the review

fix(logo readme): jsonc

---

README.md

Add an IRL example, fix links, simplify language.
- [-] Test-cases.

doc(readme): polish root README

---

packages/alias/README.md
packages/media/README.md
packages/text/README.md

As we have always done, we want to be transparent with the ecosystem. That's why I've added all the possible alternatives

doc: add more alternatives

---

.github/workflows/scorecard.yml
README.md

Add the OpenSSF Scorecard to provide a metric for our adherence to OSS best practices. 
Close #49

chore(scorecard): add

---

.github/workflows/codeql.yml
test/pjson.test.mjs

fix:(codeQL): don't run on bench/test 

---

README.md

Adding opensff best practice badge of the repo

doc: add badge

---

.github/workflows/pull-requests.yml
CONTRIBUTING.md
test/pr-prefixes.mjs
test/pull-request.mjs
test/pull-request.test.mjs

Ensure PR titles conform to Conventional Commit guidelines, per contributing policy.

setup(workflow): add check for PR title conformity

---

.github/workflows/pull-requests.yml
test/pull-request.mjs
test/pull-request.test.mjs

https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable

setup(workflow): fix PR title check security (arg → ENV)

---

packages/json5/json5.loader.mjs
packages/jsonc/jsonc.loader.mjs
packages/media/media.loader.mjs
packages/mismatched-format/mismatched-format.loader.mjs
packages/parse-filename/parse-filename.mjs
packages/parse-filename/parse-filename.spec.mjs
packages/svgx/svgx.loader.mjs
packages/text/text.loader.mjs
packages/tsx/find-esbuild-config.mjs
packages/tsx/tsx.loader.mjs
packages/types.d.ts
packages/yaml/yaml.loader.mjs

test(parse-filename): add spec

---

.github/workflows/pull-requests.yml

setup(pr-checks): re-run on PR events

---

packages/css-module/package.json

* [StepSecurity] Apply security best practices by @step-security-bot in https://github.com/nodejs-loaders/nodejs-loaders/pull/101
**Full Changelog**: https://github.com/nodejs-loaders/nodejs-loaders/compare/v1.0.1@css-module...v1.1.0@css-module

release(css-module): bumb version `1.0.1` → `1.1.0`

---

packages/text/package.json

**Full Changelog**: https://github.com/nodejs-loaders/nodejs-loaders/compare/v1.0.1@text...v1.1.0@text

release(text): bumb version `1.0.1` → `1.1.0`

---

packages/tsx/package.json

* feat(tsx): refractor internal logic by @AugustinMauroy in https://github.com/nodejs-loaders/nodejs-loaders/pull/92
* dep(tsx): update peer dependency range for esbuild by @AugustinMauroy in https://github.com/nodejs-loaders/nodejs-loaders/pull/123
* setup(workflow): add check for PR title conformity by …

release(tsx): bumb version `1.0.2` → `1.1.0`

---

packages/yaml/package.json

**Full Changelog**: https://github.com/nodejs-loaders/nodejs-loaders/compare/v1.0.1&@yaml...v1.1.0@yaml

release(yaml): bumb version `1.0.1` → `1.1.0`

---

package-lock.json
packages/alias/alias.loader.mjs
packages/alias/fixtures/tsconfig.json
packages/alias/package.json

https://github.com/nodejs-loaders/nodejs-loaders/pull/154

fix(alias): support `tsconfig` as JSON5 (trailing commas, comments)

---

package-lock.json
package.json
packages/tsx/find-esbuild-config.mjs
packages/tsx/tsx.loader.mjs
packages/yaml/yaml.loader.mjs

bump type def of node and remove ts ignore that being fixed

setup(types): remove fixed upstream issues

---

packages/alias/README.md
packages/css-module/README.md
packages/media/README.md
packages/mismatched-format/README.md
packages/svelte/README.md
packages/svgx/README.md

Hi, thanks for this repo!
Quick PR to fix the broken links to npmjs.com
--

doc(alias,css-module,media,mismatched-format,svelte,svgx): fix npm links

---

packages/alias/README.md
packages/css-module/README.md
packages/deno-npm-prefix/README.md
packages/json5/README.md
packages/jsonc/README.md
packages/media/README.md
packages/mismatched-format/README.md
packages/svelte/README.md
packages/svgx/README.md
packages/text/README.md
packages/tsx/README.md
packages/yaml/README.md

doc(all): add compatible node version badge

---

package-lock.json
package.json
packages/css-module/css-module.loader.mjs
packages/json5/json5.loader.mjs
packages/jsonc/jsonc.loader.mjs
packages/media/media.loader.mjs
packages/svelte/svelte.loader.mjs
packages/svgx/svgx.loader.mjs
packages/tsx/tsx.loader.mjs
packages/yaml/yaml.loader.mjs

Removing all remaining type issues

setup(types): update dep for upstream fixes

---

packages/svgx/README.md

doc(svgx): correct README

---

packages/tsx/package.json

* doc(all): add compatible node version badge by @JakobJingleheimer in https://github.com/nodejs-loaders/nodejs-loaders/pull/169
* setup(types): update dep for upstream fixes by @AugustinMauroy in https://github.com/nodejs-loaders/nodejs-loaders/pull/171
* fix(tsx): use source maps by @AugustinMauroy in https://github.com/nodejs-loaders/nodejs-loaders/pull/173
* doc(all): add basic usage instructions to each README by @JakobJingleheimer in https://github.com/nodejs-loaders/nodejs-loaders/pull/175
**Full Changelog**: https://github.com/nodejs-loaders/nodejs-loaders/compare/v1.1.0@tsx...v1.1.1@tsx

release(tsx): bumb version `1.1.0` → `1.1.1`

---

packages/media/README.md
packages/media/fixtures/e2e-added.mjs
packages/media/fixtures/e2e-deleted.mjs
packages/media/fixtures/e2e.mjs
packages/media/fixtures/register-additions.mjs
packages/media/fixtures/register-deletions.mjs
packages/media/fixtures/register-replacement.mjs
packages/media/fixtures/register.mjs
packages/media/media.loader.mjs
packages/media/media.spec.mjs
packages/media/media.test.mjs
packages/media/media.test.snap.cjs

Resolves https://github.com/nodejs-loaders/nodejs-loaders/discussions/167

feat(media): support modifying default file extensions list

---

packages/media/package.json

* doc(alias,css-module,media,mismatched-format,svelte,svgx): fix npm links by @karlhorky in https://github.com/nodejs-loaders/nodejs-loaders/pull/165
* doc(all): add compatible node version badge by @JakobJingleheimer in https://github.com/nodejs-loaders/nodejs-loaders/pull/169
* doc(all): add basic usage instructions to each README by @JakobJingleheimer in https://github.com/nodejs-loaders/nodejs-loaders/pull/175
* feat(media): support modifying default file extensions list by @JakobJingleheimer in https://github.com/nodejs-loaders/nodejs-loaders/pull/168
* @karlhorky made their first contribution in https://github.com/nodejs-loaders/nodejs-loaders/pull/165
**Full Changelog**: https://github.com/nodejs-loaders/nodejs-loaders/compare/v1.1.0@media...v1.2.0@media

release(media): bump version 1.1.0 → 1.2.0

---

packages/media/README.md
packages/media/media.loader.mjs

https://github.com/nodejs-loaders/nodejs-loaders/discussions/167

feat(media): add `.epdb` and `.pdf` to default list of file extensions

---

.github/workflows/ci.yml
packages/alias/alias.loader.mjs
packages/alias/alias.spec.mjs
packages/alias/alias.test.mjs
packages/css-module/css-module.spec.mjs
packages/css-module/css-module.test.mjs
packages/deno-npm-prefix/deno-npm-prefix.bench.mjs
packages/deno-npm-prefix/deno-npm-prefix.test.mjs
packages/json5/json5.test.mjs
packages/jsonc/jsonc.spec.mjs
packages/jsonc/jsonc.test.mjs
packages/media/media.loader.mjs
packages/media/media.test.mjs
packages/parse-filename/parse-filename.bench.mjs
packages/svelte/svelte.bench.mjs
packages/svelte/svelte.test.mjs
packages/tsx/find-esbuild-config.mjs
packages/tsx/tsx.bench.mjs
packages/tsx/tsx.test.mjs

Fixes #188
---
I'm not 100% familiar with this codebase, so maintainers have edit access, and I invite you to **please** commit any changes directly into this PR.

fix(windows): allow for windows support

---

packages/alias/README.md
packages/alias/alias.loader.mjs
packages/alias/alias.spec.mjs
packages/alias/alias.test.mjs
packages/alias/fixtures/customised-tsconfig-filename/e2e.mjs
packages/alias/fixtures/customised-tsconfig-filename/message.mjs
packages/alias/fixtures/customised-tsconfig-filename/package.json
packages/alias/fixtures/customised-tsconfig-filename/register.mjs
packages/alias/fixtures/customised-tsconfig-filename/tsconfig.whatever.json
packages/alias/fixtures/customised-tsconfig-full-path/e2e.mjs
packages/alias/fixtures/customised-tsconfig-full-path/message.mjs
packages/alias/fixtures/customised-tsconfig-full-path/register.mjs
packages/alias/fixtures/package.json
packages/alias/fixtures/tsconfig.whatever.json
packages/alias/get-aliases-from-tsconfig.mjs

Closes https://github.com/nodejs-loaders/nodejs-loaders/discussions/192

feat(alias): support config via `register` & `TS_NODE_PROJECT`

---

packages/alias/package.json

* doc(alias,css-module,media,mismatched-format,svelte,svgx): fix npm links by @karlhorky in https://github.com/nodejs-loaders/nodejs-loaders/pull/165
* doc(all): add compatible node version badge by @JakobJingleheimer in https://github.com/nodejs-loaders/nodejs-loaders/pull/169
* doc(all): add basic usage instructions to each README by @JakobJingleheimer in https://github.com/nodejs-loaders/nodejs-loaders/pull/175
* fix(windows): allow for windows support by @avivkeller in https://github.com/nodejs-loaders/nodejs-loaders/pull/189
* feat(alias): support config via `register` & `TS_NODE_PROJECT` by @JakobJingleheimer in https://github.com/nodejs-loaders/nodejs-loaders/pull/194
* feat(alias): support tsconfig `baseUrl` by @JakobJingleheimer in …

release(alias): bump version `2.0.1` → `2.1.0`

---

packages/tsx/package.json

Update package.json `engines` to allow current version of node.js

dep(tsx): update package `engines`
